# Generated by Django 3.0.4 on 2020-03-16 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentPacket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=100)),
                ('srcip', models.CharField(max_length=50)),
                ('dstip', models.CharField(max_length=50)),
                ('protocol', models.CharField(max_length=50)),
                ('length', models.CharField(max_length=50)),
                ('info', models.CharField(max_length=200)),
                ('carve', models.BooleanField(default=False, verbose_name='carving')),
            ],
        ),
    ]
